### ISSUE TITLE
Now button that also sets time to current time

### ISSUE THREAD

**Issue by keving119** [bsgriggs/mendix-react-date-picker#10]
Hi,

Thanks for creating this widget! I was wondering if the default Today button could be extended with a Now button that not only sets the current date of the picker, but also the current time. Right now, the today button sets the time at 00:00.

Regards,
Kevin

**Comment by bsgriggs** [comment]
Hi Kevin,
You can accomplish this using the current widget. 

1. Enable Custom Content in the Customization tab
2. disable the today button
3. Add a button to the new custom content section
![image](https://github.com/user-attachments/assets/f64a626b-d0be-4555-8b14-5732d681887b)
4. Have the button call a nanoflow that sets your datetime attribute using '{%CurrentDateTime%}'
![image](https://github.com/user-attachments/assets/98dbdee8-5a8c-428e-9e48-b51a312480be)


![image](https://github.com/user-attachments/assets/2cb07436-b860-4c9a-afd7-eefdb7f7cd1f)
