### ISSUE TITLE
Getting a warning in StudioPro console "A locale object was not found for the provided string ["nl"]."

### ISSUE THREAD

**Issue by VDSApps** [bsgriggs/mendix-react-date-picker#2]
Hi, 

Thanks for the advanced datepicker widget.

As the title says, we'regetting a warning in the console when adding the widget (we have nl_NL and en_US as languages in our apps). 
![image](https://github.com/bsgriggs/mendix-advanced-date-picker/assets/118363535/310e6642-0f21-457e-8a01-ad6e35c111f2)

Hereby the dutch translations we use:

en_US | Time | Today | Toggle calendar | Show | Select | Week | Month | Select Month | Select Year | Not selectable | Clear

nl_NL | Tijd | Vandaag | Wijzig | Toon | Selecteer | Week | Maand | Selecteer maand | Selecteer jaar | Niet mogelijk | Annuleren

Kind regards, Lourens

**Comment by bsgriggs** [comment]
Hi, 
Thank you for the help! I've added your translations to release v1.0.1 in the [marketplace](https://marketplace.mendix.com/link/component/220008). 

I've also fixed the issue generating that warning.
