### ISSUE TITLE
Add Spanish Translation es_ES

### ISSUE THREAD

**Issue by CarlesZ** [bsgriggs/mendix-react-date-picker#3]
Could you please add Spanish Translation? 

Code | Time caption | Today button text | Calendar icon text | Navigate button prefix | Select prefix | Week prefix | Month prefix | Month select label | Year select label | Disabled label | Clear button label

es_ES | Tiempo | Hoy | Cambia Calendario | Mostrar | Seleccionar | Semana | Mes | Seleccionar Mes | Seleccionar Año | No Elegible | Limpiar

Thanks!

**Comment by bsgriggs** [comment]
Hi Carles,
Thank you for translating! I've added this to the marketplace release v1.1.0
