### ISSUE TITLE
Range issue

### ISSUE THREAD

**Issue by dloops** [bsgriggs/mendix-react-date-picker#7]
Hello,

I am not being able to make range work properly on Studio Pro 9.24.16. When I click on the dates in the calendar, nothing gets selected.

![image](https://github.com/bsgriggs/mendix-advanced-date-picker/assets/92545031/44dd8a6f-9cd2-48c3-9132-05bd3d5ae1fd)

![image](https://github.com/bsgriggs/mendix-advanced-date-picker/assets/92545031/5a1e63df-0f24-474a-9c03-bcab3932b4eb)

Thanks for the great widget!

**Comment by bsgriggs** [comment]
Hi. Does the user have database access to those attributes?

**Comment by dloops** [comment]
Yes, read and write. I tried other widget from the marketplace with a similar setup and it worked

**Comment by bsgriggs** [comment]
It works for me in 9.24.16
![image](https://github.com/bsgriggs/mendix-advanced-date-picker/assets/47681665/5d1c29f3-8718-4594-b0b9-49407fda9d49)
---
![image](https://github.com/bsgriggs/mendix-advanced-date-picker/assets/47681665/9369dbb1-2e46-4b70-8ddf-5bdaa5355468)
---
Can you include screenshots of all of the widget setting tabs?
![image](https://github.com/bsgriggs/mendix-advanced-date-picker/assets/47681665/ad2a2f15-7b68-4d26-beeb-b8e496125751)
![image](https://github.com/bsgriggs/mendix-advanced-date-picker/assets/47681665/6c1be673-a0ac-4c30-982b-2046a4df332f)
![image](https://github.com/bsgriggs/mendix-advanced-date-picker/assets/47681665/38b3ba7a-e2f6-4c35-b08d-cd9f4f6989c3)
![image](https://github.com/bsgriggs/mendix-advanced-date-picker/assets/47681665/5304ba1c-8ad4-43f1-80f2-4d3150952c53)

**Comment by dloops** [comment]
Hello,

I tried deleting the widget from the project and adding it again from the marketplace and it simply worked, not sure what happened. I had only edited the sources in the first tab, the rest of the the tabs were left with default, and it was inside a group box, but now it works both inside and out. Thank you!

**Comment by bsgriggs** [comment]
Strange.
