### ISSUE TITLE
Disable the calendar when attribute is readonly

### ISSUE THREAD

**Issue by amitsharma9zurichcom** [bsgriggs/mendix-react-date-picker#8]
When Date and Time attribute marked as read only on the page and developer used customization as 
show icon **true** and 
show icon inside **false** 
then calendar icon should not still remain clickable. it should also disabled.

![AdvanceDatePicker_NotEditable](https://github.com/bsgriggs/mendix-advanced-date-picker/assets/166385513/2b451026-dbdf-43db-8f22-f5fdb9b32e94)

**Comment by bsgriggs** [comment]
Hi Amit, this should be fixed in marketplace release 1.4.0
