### ISSUE TITLE
Calendar pop-up is not getting closed 

### ISSUE THREAD

**Issue by arundubey07** [bsgriggs/mendix-react-date-picker#9]
Hi, 

Whenever we are selecting date format as custom the calendar pop up is not getting closed after selecting the date. It is working fine if we are going with default option. 
In our project I have selected the format as custom and setting  the format as "dd.MM.yyyy" so after selecting the date the calendar window is still in open form.

Thanks

**Comment by bsgriggs** [comment]
Hi there,

I believe I have resolved your issue in the new release [v1.4.2](https://github.com/bsgriggs/mendix-advanced-date-picker/releases/download/v1.4.2/mendix.AdvancedDatePicker.mpk). Please let me know if you have any questions.
